version: '3.8'

services:
  hvac-site:
    build: .
    container_name: birmingham-hvac
    ports:
      - "80:3000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - hvac-network

networks:
  hvac-network:
    driver: bridge