version: '3.8'

services:
  # Nginx SSL Proxy
  nginx-ssl:
    image: nginx:alpine
    container_name: hvac-nginx-ssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginx configuration
      - ./nginx-ssl-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-ssl-config/hvac35242.conf:/etc/nginx/conf.d/default.conf:ro
      
      # SSL certificates (create these directories on host)
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
      
      # Let's Encrypt webroot (for certificate challenges)
      - /var/www/certbot:/var/www/certbot:ro
      
      # Nginx logs
      - nginx-logs:/var/log/nginx
      
      # DH parameters
      - /etc/ssl/dhparams.pem:/etc/ssl/dhparams.pem:ro
    depends_on:
      - hvac-app
    restart: always
    networks:
      - hvac-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js HVAC Application
  hvac-app:
    build: .
    container_name: hvac-app
    ports:
      - "3000:3000"  # Only exposed internally
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - hvac-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Application logs
      - app-logs:/app/logs

  # Certbot for Let's Encrypt (optional - use if not using Sectigo)
  certbot:
    image: certbot/certbot
    container_name: hvac-certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - certbot-logs:/var/log/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@hvac35242.com --agree-tos --no-eff-email -d hvac35242.com -d www.hvac35242.com
    networks:
      - hvac-network
    profiles:
      - letsencrypt  # Only start if profile is specified

  # SSL Certificate Renewal (for Let's Encrypt)
  certbot-renewal:
    image: certbot/certbot
    container_name: hvac-certbot-renewal
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - certbot-logs:/var/log/letsencrypt
    command: renew --webroot --webroot-path=/var/www/certbot
    networks:
      - hvac-network
    profiles:
      - renewal  # Only start when running renewal

volumes:
  nginx-logs:
    driver: local
  app-logs:
    driver: local
  certbot-logs:
    driver: local

networks:
  hvac-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16